Library/Models/Patron.cs
using System.Collections.Generic;

namespace Library.Models
{
    public class Patron
    {
        public Patron()
        {
            this.Books = new HashSet<BookPatron>();
        }

        public int PatronId { get; set; }
        public string PatronName { get; set;}
        public virtual ICollection<BookPatron> Books { get; set; }
        //public virtual ICollection<Checkouts> Copies { get; set; }
    }
}

Library/Controllers/PatronsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using System.Linq;
using Library.Models;
//new for authorizing
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Library.Controllers
{
    [Authorize]
    public class PatronsController : Controller
    {
        private readonly LibraryContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public PatronsController(UserManager<ApplicationUser> userManager, LibraryContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public ActionResult Index()
        {
        List<Patron> model = _db.Patrons.ToList();
        model.Sort((x, y) => string.Compare(x.PatronName, y.PatronName));
        return View(model);
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Patron patron, int BookId)
        {
            _db.Patrons.Add(patron);
            if (BookId != 0)
            {
                _db.BookPatron.Add(new BookPatron() { BookId = BookId, PatronId = patron.PatronId });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisPatron = _db.Patrons
                .Include(patron => patron.Books)
                .ThenInclude(join => join.Book)
                // .Include(patron => patron.Copies) // eh?
                // .ThenInclude(join => join.Copy)
                // OR ...
                // List<Copy> foundCopies = _db.Copies.Where(copy => copy.PatronId == id).ToList();
                //ViewBag.foundCopies = foundCopies;
                // .Include(patron => patron.User)
                .FirstOrDefault(patron => patron.PatronId == id);
            // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            // ViewBag.IsCurrentUser = userId != null ? userId == thisPatron.User.Id : false;
            return View(thisPatron);
        }

        public ActionResult Edit(int id)
        {
            var thisPatron = _db.Patrons.FirstOrDefault(patron => patron.PatronId == id);
            return View(thisPatron);
        }

        [HttpPost]
        public ActionResult Edit(Patron patron)
        {
            _db.Entry(patron).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisPatron = _db.Patrons.FirstOrDefault(patron => patron.PatronId == id);
            return View(thisPatron);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisPatron = _db.Patrons.FirstOrDefault(patron => patron.PatronId == id);
            _db.Patrons.Remove(thisPatron);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddBook(int id)
        {
            var thisPatron = _db.Patrons.FirstOrDefault(patrons => patrons.PatronId == id);
            ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
            ViewBag.CheckedOut = new SelectList(_db.Books, "BookId", "CheckedOut");
            return View(thisPatron);
        }

        [HttpPost]
        public ActionResult AddBook(Patron patron, int BookId)
        {
            if (BookId != 0)
            {
                _db.BookPatron.Add(new BookPatron() { BookId = BookId, PatronId = patron.PatronId });
            }
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = patron.PatronId});
        }

        public ActionResult DeleteBook(int joinId)
        {
            var joinEntry = _db.BookPatron.FirstOrDefault(entry => entry.BookPatronId == joinId);
            _db.BookPatron.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Library/Views/Patrons/AddBook.cshtml
@{
    Layout = "_Layout";
}

@using Library.Models
@model Library.Models.Patron

<h2>Checkout a Book</h2>
<hr>
<h4>Patron Name: @Html.DisplayFor(model => model.PatronName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PatronId)

    @Html.Label("Select Book")
    @Html.DropDownList("BookId")

    @*
    <p>Select "Check Out" if you would like to check this book out:</p>
    @Html.Label("Check Out")
    @Html.RadioButtonFor("CheckedOut", false)
    @Html.RadioButtonFor("CheckedOut", true)
    *@

    <input type="submit" value="Complete Checkout">
}
<p>@Html.ActionLink("Back to previous page", "Index")</p>

Library/Views/Patrons/Create.cshtml
@{
    Layout = "_Layout";
}

@model Library.Models.Patron

<h2>Add a New Patron</h2>
<hr>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.PatronName)
    @Html.TextBoxFor(model => model.PatronName)

    <input type="submit" value="Add new patron" class="btn btn-default" />
}
<p>@Html.ActionLink("Show All Patrons", "Index")</p>

Library/Views/Patrons/Delete.cshtml
@{
    Layout = "_Layout";
}

@model Library.Models.Patron

<h2>Are you sure you want to delete this?</h2>
<hr>
<p>Patron Name: @Html.DisplayFor(model => model.PatronName)</p>
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<p>@Html.ActionLink("Back to Patrons", "Index")</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

Library/Views/Patrons/Details.cshtml
@{
    Layout = "_Layout";
}

@model Library.Models.Patron

<h2>Patron Details</h2>
<hr />
<h3>Patron Name: @Html.DisplayFor(model => model.PatronName)</h3>

@if(@Model.Books.Count == 0)
{
    <p>This patron has not checked out any books</p>
}
else
{
    <h4>Books this patron has checked out:</h4>
    <ul>
    @foreach(var join in Model.Books)
    {
        <li>@join.Book.Title</li>
        @using (Html.BeginForm("DeleteBook", "Patrons"))
        {
        @Html.Hidden("joinId", @join.BookPatronId)
        <input type="submit" value="Delete"/>
        }
    }
    </ul>
}

<p>@Html.ActionLink("Back to Patron List", "Index")</p>
<p>@Html.ActionLink("Edit Patron", "Edit", new { id = Model.PatronId })</p>
<p>@Html.ActionLink("Checkout Book", "AddBook", new { id = Model.PatronId })</p>
<p>@Html.ActionLink("Delete Patron", "Delete", new { id = Model.PatronId })</p>

Library/Views/Patrons/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Patron

<h2>Edit</h2>
<hr>
<h4>Edit this book: @Html.DisplayFor(model => model.PatronName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatronId)

  @Html.LabelFor(model => model.PatronName)
  @Html.TextBoxFor(model => model.PatronName)

  <input type="submit" value="Save">
}

<p>@Html.ActionLink("Show all Patrons", "Index", "Patrons")</p>
<p>@Html.ActionLink("Library Home", "Index", "Home")</p>

Library/Views/Patrons/Index.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models;
@model List<Library.Models.Patron>;

<h2>Patrons</h2>
<hr>
@if (@Model.Count == 0)
{
  <h3>No models have been added yet!</h3>
}

@foreach (Patron patron in Model)
{
  <li>@Html.ActionLink($"{patron.PatronName}", "Details", new { id = patron.PatronId })</li>
}

<p>@Html.ActionLink("Add new patron", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>