Library/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
    public class Book
    {
        public Book()
        {
            this.Patrons = new HashSet<BookPatron>();
            this.Authors = new HashSet<AuthorBook>();
        }
        public int BookId { get; set; }
        public string Title { get; set; }
        public bool CheckedOut { get; set; } = false;
        // Stretch:
        // [Display(Name="Date")]
        // [DataType(DataType.Date)]
        // [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd")]
        // public DateTime CheckOutDate { get; set; } = DateTime.Now;
        [Display(Name="Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd")]
        public DateTime DueDate { get; set; } = DateTime.Now.AddDays(14); // View: @hidden
        public bool Overdue { get; set; } = false;
        public virtual ApplicationUser User { get; set; }
        // public int CopyId { get; set; }
        // public virtual Copy Copy { get; set; }
        public virtual ICollection<BookPatron> Patrons { get; }
        public ICollection<AuthorBook> Authors { get; set; }
        // public virtual ICollection<Checkout> Copies { get; set; }
    }
}

Library/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Library.Controllers
{
    [Authorize]
    public class AuthorsController : Controller
    {
        private readonly LibraryContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public AuthorsController(UserManager<ApplicationUser> userManager, LibraryContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public ActionResult Index()
        {
            List<Author> model = _db.Authors.ToList();
            model.Sort((x, y) => string.Compare(x.AuthorName, y.AuthorName));
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Author author)
        {
            _db.Authors.Add(author);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisAuthor = _db.Authors
                .Include(author => author.Books)
                .ThenInclude(join => join.Book)
                .FirstOrDefault(author => author.AuthorId == id);
            return View(thisAuthor);
        }

        public ActionResult Edit(int id)
        {
            var thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
            if (thisAuthor == null)
            {
                return RedirectToAction("Details", new {id = id});
            }
            ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
            return View(thisAuthor);
        }

        [HttpPost]
        public ActionResult Edit(Author author, int BookId)
        {
            if (BookId !=0)
            {
                _db.AuthorBook.Add(new AuthorBook() { BookId = BookId, AuthorId = author.AuthorId });
            }
            _db.Entry(author).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = author.AuthorId });
        }

        public ActionResult Delete(int id)
        {
            var thisAuthor = _db.Authors
                .Include(author => author.Books)
                .ThenInclude(join => join.Book)
                .FirstOrDefault(author => author.AuthorId == id);
            if (thisAuthor == null)
            {
                return RedirectToAction("Details", new { id= id});
            }
            return View(thisAuthor);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, int joinId)
        {
            if (joinId != 0)
            {
                var joinEntry = _db.AuthorBook.FirstOrDefault(entry => entry.AuthorBookId == joinId);
                _db.AuthorBook.Remove(joinEntry);
                var thisAuthor = _db.Authors
                    .Include(author => author.Books)
                    .ThenInclude(join => join.Book)
                    .FirstOrDefault(author => author.AuthorId == id);
                _db.Authors.Remove(thisAuthor);
                _db.SaveChanges();
            }
            else
            {
                var thisAuthor = _db.Authors
                    .Include(author => author.Books)
                    .ThenInclude(join => join.Book)
                    .FirstOrDefault(author => author.AuthorId == id);
                _db.Authors.Remove(thisAuthor);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteBook(int joinId)
        {
            var joinEntry = _db.AuthorBook.FirstOrDefault(entry => entry.AuthorBookId == joinId);
            _db.AuthorBook.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddBook(int joinId, int id)
        {
            var thisAuthor = _db.Authors.FirstOrDefault(authors => authors.AuthorId == id);
            ViewBag.BookId = new SelectList(_db.Books, "BookId", "Title");
            return View(thisAuthor);
        }

        [HttpPost]
        public ActionResult AddBook(Author author, int BookId)
        {
            if (BookId != 0)
            {
                _db.AuthorBook.Add(new AuthorBook() { BookId = BookId, AuthorId = author.AuthorId });
            }
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = author.AuthorId});
        }
    }
}

Library/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Library.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly LibraryContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public BooksController(UserManager<ApplicationUser> userManager, LibraryContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public ActionResult Index()
        {
            List<Book> model = _db.Books.ToList();
            model.Sort((x, y) => string.Compare(x.Title, y.Title));
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "AuthorName");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Book book, int AuthorId)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            book.User = currentUser;
            _db.Books.Add(book);
            if (AuthorId != 0)
            {
                _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId});
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisBook = _db.Books
                .Include(book => book.Authors)
                .ThenInclude(join => join.Author)
                .Include(book => book.Patrons)
                .ThenInclude(join => join.Patron)
                .Include(book => book.User)
                .FirstOrDefault(book => book.BookId == id);
            return View(thisBook);
        }

        public ActionResult Edit(int id)
        {
            var thisBook = _db.Books.FirstOrDefault(books => books.BookId == id);
            if (thisBook == null)
            {
                return RedirectToAction("Details", new {id = id});
            }
            ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "AuthorName");
            //ViewBag.PatronId = new SelectList(_db.Patrons, "PatronId", "Name");
            return View(thisBook);
        }

        [HttpPost]
        public ActionResult Edit(Book book, int AuthorId, int PatronId)
        {
            if (AuthorId !=0)
            {
                _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId });
            }
            _db.Entry(book).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = book.BookId });
        }

        public ActionResult Delete(int id)
        {
            var thisBook = _db.Books
                .Include(book => book.Authors)
                .ThenInclude(join => join.Author)
                .FirstOrDefault(book => book.BookId == id);
            if (thisBook == null)
            {
                return RedirectToAction("Details", new {id = id});
            }
            return View(thisBook);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, int joinId)
        {
            if (joinId != 0)
            {
                var joinEntry = _db.AuthorBook.FirstOrDefault(entry => entry.AuthorBookId == joinId);
                _db.AuthorBook.Remove(joinEntry);
                var thisBook = _db.Books
                    .Include(book => book.Authors)
                    .ThenInclude(join => join.Author)
                    .FirstOrDefault(book => book.BookId == id);
                _db.Books.Remove(thisBook);
                _db.SaveChanges();
            }
            else
            {
                var thisBook = _db.Books
                    .Include(book => book.Authors)
                    .ThenInclude(join => join.Author)
                    .FirstOrDefault(book => book.BookId == id);
                _db.Books.Remove(thisBook);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteAuthor(int joinId)
        {
            var joinEntry = _db.AuthorBook.FirstOrDefault(entry => entry.AuthorBookId == joinId);
            _db.AuthorBook.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddAuthor(int joinId, int id)
        {
            var thisBook = _db.Books.FirstOrDefault(books => books.BookId == id);
            ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "AuthorName");
            return View(thisBook);
        }

        [HttpPost]
        public ActionResult AddAuthor(Book book, int AuthorId)
        {
            if (AuthorId != 0)
            {
                _db.AuthorBook.Add(new AuthorBook() { AuthorId = AuthorId, BookId = book.BookId });
            }
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = book.BookId});
        }
    }
}

Library/Views/Books/AddAuthor.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models
@model Library.Models.Book

<h2>Add an Author to Existing Book: @Html.DisplayFor(model => model.Title)</h2>
<hr>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.BookId)

  @Html.Label("Select Author")
  @Html.DropDownList("AuthorId", " ")

  <input type="submit" value="Save">
}

<p>@Html.ActionLink("Back to book details", "Details", new { id = Model.BookId })</p>

Library/Views/Books/Create.cshtml
@{
    Layout = "_Layout";
}

@model Library.Models.Book

<h2>Add a Title</h2>
<hr>
@using (Html.BeginForm())
{

    @Html.LabelFor(model => model.Title)
    @Html.TextBoxFor(model => model.Title)

    //Stretch
    @* @Html.HiddenFor("AuthorId")
    @Html.LabelFor("Add new author")
    @Html.TextBoxFor("AuthorId")

    <p>--OR--</p> *@

    @Html.Label("Select existing author")
    @Html.DropDownList("AuthorId", " ")

    <input type="submit" value="Add new book title" class="btn btn-default">
}
<p>@Html.ActionLink("Show all books", "Index")</p>
<p>@Html.ActionLink("Library Home", "Index", "Home")</p>

Library/Views/Books/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<h2>Are you sure you want to delete this?</h2>
<hr>
@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Books", "Index")

Library/Views/Books/Details.cshtml
@{
  Layout ="_Layout";
}

@model Library.Models.Book

<h2>Book Details</h2>
<hr />

<h3>@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)</h3>
<h4>Checked Out? @Html.DisplayFor(model => model.CheckedOut)</h4>
@*<h4> Check out to: @Html.DisplayFor("PatronName")</h4>*@
<h4>Due Date: @Model.DueDate.ToString("MM dd, yyyy")</h4>
@*<h4>Overdue: @Html.DisplayFor(model => model.Overdue)</h4>*@
@* @if (Model.DueDate > DateTime.Now)
{
  Model.Overdue == false;
}
else{
  Model.Overdue == true;
} *@
<br>
@if(@Model.Authors.Count == 0)
{
  <p>This book does not belong to any authors.</p>
  <p>@Html.ActionLink("Add Author to This Book", "AddAuthor", "Books", new { id = Model.BookId }) || @Html.ActionLink("Create New Author", "Create", "Authors")</p>
  <hr />
}
else
{
  <h4>Author(s) this book belongs to:</h4>
  <ul>
  @foreach(var join in Model.Authors)
  {
    <li>@join.Author.AuthorName</li>
    @using (Html.BeginForm("DeleteAuthor", "Books"))
    {
      @Html.Hidden("joinId", @join.AuthorBookId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}
<h4>This book has been checked out by:</h4>
  @foreach(var join in Model.Patrons)
  {
    <p>@join.Patron.PatronName</p>
  }

<p>@Html.ActionLink("View All Books", "Index") || @Html.ActionLink("Edit Book", "Edit", new { id = Model.BookId }) || @Html.ActionLink("Add an Author", "Create", "Authors") || @Html.ActionLink("Delete Book", "Delete", new { id = Model.BookId })</p>

Library/Views/Books/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<h2>Edit</h2>
<hr>
<h4>Edit this book: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.BookId)

  @Html.LabelFor(model => model.Title)
  @Html.TextBoxFor(model => model.Title)

  <br>

  @Html.LabelFor(model => model.CheckedOut)
  @Html.CheckBoxFor(model => model.CheckedOut)

  <br>

  @Html.Label("Select Author")
  @Html.DropDownList("AuthorId", "-No Update-")

  @Html.HiddenFor(model => model.DueDate)

  @Html.HiddenFor(model => model.Overdue)

  <input type="submit" value="Save">
}

<p>@Html.ActionLink("Show all books", "Index", "Books")</p>
<p>@Html.ActionLink("Library Home", "Index", "Home")</p>

Library/Views/Books/Index.cshtml
@{
    Layout = "_Layout";
}

@using Library.Models;
@using System.Security.Claims
@model IEnumerable<Library.Models.Book>

<h2>Books</h2>
<hr>
@if (Model.Any())
{
    <ul>
    @foreach (Book book in Model)
    {
        <li>@Html.ActionLink($"{book.Title}", "Details", new { id = book.BookId})</li>
    }
    </ul>
}
else
{
    <h3>There are no books in this library</h3>
}

<p>@Html.ActionLink("Add a New Book to a New Author","Create", "Authors")
<p>@Html.ActionLink("Add a New Book to an Existing Author", "Create")</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>